### ISSUE TITLE
Fix hex regex

### ISSUE THREAD

**Issue by cxcorp** [cxcorp/cyberpunk2077-hacking-solver#2]
https://github.com/cxcorp/cyberpunk2077-hacking-solver/blob/fb09dfccc655d7b7baea1a03404b282b95000337/pages/index.tsx#L31

Curr only checks first character lol

**Comment by ThatsNinja** [comment]
Please see https://github.com/cxcorp/cyberpunk2077-hacking-solver/pull/6.

Sorry if I'm cluttering up your issues or PRs.

**Comment by cxcorp** [comment]
Thank you!

**Comment by cxcorp** [comment]
Closed by #6
