### ISSUE TITLE
Add Test Coverage

### ISSUE THREAD

**Issue by ThatsNinja** [cxcorp/cyberpunk2077-hacking-solver#7]
The project would benefit quite a bit from test coverage, enabling work on features with less ramp-up time and lower risk to existing functionality.

Here's a branch adding unit test coverage to 'main':
https://github.com/ThatsNinja/cyberpunk2077-hacking-solver/tree/add-test-coverage

**Comment by cxcorp** [comment]
Definitely a good idea! The project was mostly banged out as fast as possible, so there's been a few bug fixes regarding the solver and sequence optimizer.

**Comment by ThatsNinja** [comment]
I will open a PR for this first, then. I'd like to merge the testing changes to main, merge pull, and write tests for the changes in my other feature branch (for sequence optimizer constraints) before opening a PR for that.

**Comment by ThatsNinja** [comment]
(Please see PR #8)
